version: 2
project_name: pwd_gen

builds:
  - id: pwd_gen
    main: .
    binary: pwd_gen
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - id: pwd_gen
    ids:
      - pwd_gen
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    builds_info:
      mtime: "{{ .CommitTimestamp }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
