---
# @see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# @see https://github.com/actions/virtual-environments
name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency: pwd-gen-release
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Check
        run: make check

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
